Fix#997: Adding extra form field to confirm the download permissions & Fixing minor UI issues
1-Platform/video-library pull request #163
Opened 2021-08-04 17:42 UTC by ghanlohar

# Fixes - ONEPLAT-997

# Explain the feature/fix
- Adding extra form field to confirm the download permissions
- Fixing minor UI issues

## Does this PR introduce a breaking change
No

2021-08-06 04:51 UTC, deshmukhmayur approved these changes

2021-08-06 04:51 UTC, deshmukhmayur commented on video-library-client/src/video/VideoForm.js
> +          {`${advanceFields ? "Hide" : "Show"} Advanced Fields`}
```suggestion
          { advanceFields ? 'Hide' : 'Show' } Advanced Fields
```

2021-08-06 04:52 UTC, deshmukhmayur requested changes
See the above comment^

2021-08-09 07:32 UTC, ghanlohar commented on video-library-client/src/video/VideoForm.js
> +          {`${advanceFields ? "Hide" : "Show"} Advanced Fields`}
Updated

2021-08-09 07:36 UTC, riginoommen approved these changes

2021-08-09 13:25 UTC, deshmukhmayur approved these changes

2021-08-09 13:25 UTC, merged