Feat#1687: Written unit tests for video library SPA
1-Platform/video-library pull request #207
Opened 2022-01-20 18:22 UTC by ghanlohar

# Closes/Fixes/Resolves

### 
ONEPLAT-1687, Closing #206 
# Explain the feature/fix

- Written unit test cases for video library SPA

## Does this PR introduce a breaking change

No

## Screenshots

<details>
<summary>View Screenshots</summary>

<img width="694" alt="Screenshot 2022-01-20 at 11 49 33 PM" src="https://user-images.githubusercontent.com/5575651/150398202-650019e0-a4b9-4708-87e3-af22b2a4ca1b.png">

</details>

### Ready-for-merge Checklist

- [x] Expected files: all files in this pull request are related to one feature request or issue (no stragglers)?
- [x] Does the change have appropriate unit tests?
- [x] Did tests pass?
- [x] Did you update or add any necessary documentation (README.md, WHY.md, etc.)?
- [x] Was this feature demo'd and the design review approved?

2022-01-24 06:22 UTC, deshmukhmayur approved these changes

2022-01-24 06:23 UTC, deshmukhmayur requested changes
@ghanlohar Can you address the lgtm comments for unused imports?
Other than that, it's good to merge.

2022-01-24 07:25 UTC, ghanlohar commented
> @ghanlohar Can you address the lgtm comments for unused imports? Other than that, it's good to merge.

@deshmukhmayur Fixed

2022-01-28 07:22 UTC, hybridx approved these changes

2022-01-28 07:23 UTC, riginoommen approved these changes

2022-02-01 08:40 UTC, deshmukhmayur approved these changes

2022-02-01 08:40 UTC, merged