chore(banner) - Added non-native link
1-Platform/video-library pull request #255
Opened 2022-11-14 14:56 UTC by hybridx

2022-11-14 15:08 UTC, riginoommen requested changes

2022-11-14 15:08 UTC, riginoommen commented on video-library-client/src/services/Helpers.js
> +  return fetch(`${process.env.REACT_APP_API_UR_NON_NATIVE}`, {
```suggestion
  return fetch(`${process.env.REACT_APP_API_URL_NON_NATIVE}`, {
```
Update .env.example also

2022-11-14 15:12 UTC, hybridx commented on video-library-client/src/services/Helpers.js
> +  return fetch(`${process.env.REACT_APP_API_UR_NON_NATIVE}`, {
Added

2022-11-14 15:13 UTC, riginoommen reviewed
Remove the duplicate environment variables

2022-11-14 15:13 UTC, riginoommen commented on video-library-client/.env.example
> +REACT_APP_API_UR_NON_NATIVE=
```suggestion
REACT_APP_API_URL_NON_NATIVE=
```

2022-11-15 11:30 UTC, hybridx commented on video-library-client/package.json
> +    "start": "PORT=4200 react-scripts start",
Because localhost:3000 isn't available in the allowed origin of preprod instances 

```
  "allowed-origins": [
    "https://dev.one.redhat.com",
    "https://qa.one.redhat.com",
    "https://localhost:5500",
    "https://localhost:4200",
    "http://localhost:5500",
    "https://dev.foo.redhat.com:5500",
    "http://dev.foo.redhat.com:5500",
    "http://localhost:4200",
    "https://stage.one.redhat.com"
  ],
  ```

2022-11-15 11:31 UTC, hybridx commented on video-library-client/package.json
> +    "start": "PORT=4200 react-scripts start",
@riginoommen I can paste the JWT here but it would be a breach of privacy. Let me know if you want to see the token as well

2022-11-15 12:59 UTC, riginoommen approved these changes

2022-11-16 11:00 UTC, merged