chore: disable add video button and update banner information
1-Platform/video-library pull request #262
Opened 2022-11-17 09:58 UTC by ayushsatyam146

Disabled the Add video button and updated the Banner.

Previous:

![image](https://user-images.githubusercontent.com/55888723/202415633-166b109f-a06a-437b-8b89-f71eb1e10c78.png)

Current:

![image](https://user-images.githubusercontent.com/55888723/202415236-5cd16320-09dc-4296-a94e-16df11af5cc6.png)

2022-11-17 10:07 UTC, hybridx approved these changes
LGTM. @ayushsatyam146 can you please bump up the minor version in package.json

2022-11-17 12:44 UTC, hybridx approved these changes

2022-11-17 12:49 UTC, riginoommen commented on video-library-client/src/App.js
> +              href="https://videos.learning.redhat.com/"
Convert this as an environment variable

2022-11-17 12:49 UTC, riginoommen commented on video-library-client/src/App.js
> +              In response to Media Space (http://videos.learning.redhat.com/)
```suggestion
              In response to Media Space (http://videos.learning.redhat.com/)
```
Convert this as an environment variable

2022-11-17 12:49 UTC, riginoommen commented on video-library-client/src/App.js
> +              the video library is about to be decommissioned on 31 Dec'22.
```suggestion
              the video library is about to be decommissioned on 31st Dec'22.
```

2022-11-17 12:50 UTC, riginoommen requested changes
Please see above changes

2022-11-18 05:18 UTC, riginoommen approved these changes

2022-11-18 05:18 UTC, riginoommen approved these changes

2022-11-18 11:54 UTC, hybridx approved these changes

2022-11-18 11:54 UTC, merged