Fix(#941): Removing apollo federated schema.
1-Platform/video-library pull request #56
Opened 2020-12-22 11:11 UTC by ghanlohar

# Fixes - ONEPLAT-941

# Explain the feature/fix

1. Removing apollo federated schema.

## Does this PR introduce a breaking change
No

2020-12-22 11:16 UTC, deshmukhmayur requested changes

2020-12-22 11:16 UTC, deshmukhmayur commented on video-library-service/package.json
>      "@types/cookie-parser": "1.4.2",
Also remove the cookie parser, body parser, cors, and husky as they're not used.
And any other packages that are not needed.

2020-12-22 11:56 UTC, riginoommen approved these changes

2020-12-23 10:40 UTC, deshmukhmayur approved these changes

2020-12-23 10:44 UTC, merged