Fix(#941): Replacing nested resolvers with inline requests to reduce response time.
1-Platform/video-library pull request #58
Opened 2020-12-23 11:43 UTC by ghanlohar

# Fixes - ONEPLAT-941

# Explain the feature/fix

Replacing nested resolvers with inline requests to reduce listVideos response time.

## Does this PR introduce a breaking change
No

2020-12-23 12:15 UTC, riginoommen requested changes

2020-12-23 12:15 UTC, riginoommen commented on video-library-service/service.ts
> +  //extensions
```suggestion
  extensions
```

2020-12-23 12:15 UTC, riginoommen commented on video-library-service/src/resolver.ts
> +\t${video.description || `A Demo was recently created for ${video.title} by ${userDetails?.name}.`}
```suggestion
\t${video.description || `A demo was recently created for ${video.title} by ${userDetails?.name}.`}
```

2020-12-23 12:15 UTC, riginoommen commented on video-library-service/src/resolver.ts
> +          console.log("User Details", userDetails);
```suggestion
          
```

2020-12-23 16:13 UTC, ghanlohar commented on video-library-service/service.ts
> +  //extensions
Done!

2020-12-23 16:13 UTC, ghanlohar commented on video-library-service/src/resolver.ts
> +\t${video.description || `A Demo was recently created for ${video.title} by ${userDetails?.name}.`}
Done!

2020-12-24 06:16 UTC, riginoommen approved these changes

2020-12-24 17:13 UTC, merged